name: CI

on:
  push:
    branches: [ main ]

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: yarn
      - run: yarn install --frozen-lockfile
      - run: yarn test
      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      - name: 🚀 Build app
        run: eas build --platform android --non-interactive --no-wait
      - name: Install Netlify
        run: npm install netlify-cli -g
      - name: Build web
        run: yarn build-web
      - name: Deploy to Netlify
        id: netlify_deploy
        run: |
          netlify deploy \
          --dir ./dist \
          --site ${{ secrets.NETLIFY_SITE_ID }} \
          --auth ${{ secrets.NETLIFY_TOKEN }}
      - name: Run e2e tests with Cypress
        uses: cypress-io/github-action@v6
        with:
          start: yarn web
          browser: chrome
          wait-on: 'http://localhost:8081/'
          wait-on-timeout: 180
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './coverage/lcov-report'

  deploy_coverage:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    needs: build_test
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
